/// The default content taxonomy: a broad starter tree of domains and subjects
/// covering general knowledge, academics, entertainment, and competitive-exam
/// topics.
///
/// Seeded via the admin panel's "Seed default taxonomy" button. Everything is
/// created HIDDEN (isActive: false) so an empty category never shows up to
/// users — unhide a subject from Admin > Domains & Subjects once you've
/// uploaded questions for it.
///
/// Seeding is idempotent and additive: it only creates domains/subjects whose
/// slug id doesn't already exist. It never renames, re-hides, deletes, or
/// otherwise touches anything already in your database — so running it twice
/// is harmless, and it will not disturb the domains you've already built up.
///
/// Generated data — edit the map below to change what gets seeded.
class DefaultTaxonomy {
  /// domain name -> list of subject names.
  static const Map<String, List<String>> tree = {
    'World & Geography': [
      'Continents',
      'Countries',
      'Capitals',
      'Flags',
      'Currencies',
      'Time Zones',
      'World Maps',
      'Rivers',
      'Lakes',
      'Mountains',
      'Deserts',
      'Islands',
      'Oceans & Seas',
      'Waterfalls',
      'National Parks',
      'Famous Landmarks',
      'World Heritage Sites',
      'Borders',
      'Countries by Population',
      'Countries by Area',
    ],
    'India': [
      'Indian States',
      'Union Territories',
      'State Capitals',
      'Indian Geography',
      'Indian History',
      'Indian Culture',
      'Indian Constitution',
      'Indian Polity',
      'Indian Economy',
      'Indian Rivers',
      'Indian Mountains',
      'Indian National Parks',
      'Indian Monuments',
      'Indian Festivals',
      'Indian Languages',
      'Indian Cuisines',
      'Indian Art',
      'Indian Literature',
      'Indian Awards',
      'Indian Firsts',
      'Important Days',
      'Famous Indians',
      'Indian Government Schemes',
      'Indian Defence',
      'Indian Space Programme',
    ],
    'History': [
      'Ancient History',
      'Medieval History',
      'Modern History',
      'World Wars',
      'Indian Freedom Movement',
      'Ancient Civilizations',
      'Roman Empire',
      'Greek Civilization',
      'Egyptian Civilization',
      'Mughal Empire',
      'British Empire',
      'Famous Battles',
      'Famous Kings & Queens',
      'Historical Events',
      'Historical Personalities',
      'Inventions Through History',
      'Historical Places',
      'Ancient Religions',
      'Historical Dates',
      'Dynasties & Empires',
    ],
    'Science': [
      'Physics',
      'Chemistry',
      'Biology',
      'Astronomy',
      'Earth Science',
      'Environmental Science',
      'Human Body',
      'Animals',
      'Plants',
      'Genetics',
      'Microbiology',
      'Ecology',
      'Space Science',
      'Scientific Discoveries',
      'Famous Scientists',
      'Inventions',
      'Scientific Instruments',
      'Everyday Science',
      'Science Facts',
      'Nobel Prizes in Science',
    ],
    'Mathematics': [
      'Arithmetic',
      'Algebra',
      'Geometry',
      'Trigonometry',
      'Calculus',
      'Probability',
      'Statistics',
      'Number Systems',
      'Percentages',
      'Profit & Loss',
      'Ratio & Proportion',
      'Time & Work',
      'Time, Speed & Distance',
      'Permutation & Combination',
      'Mensuration',
      'Data Interpretation',
      'Logical Mathematics',
      'Mental Maths',
      'Number Puzzles',
    ],
    'Technology & Computers': [
      'Computer Fundamentals',
      'Programming',
      'Flutter',
      'Dart',
      'Java',
      'Python',
      'C/C++',
      'JavaScript',
      'Web Development',
      'Databases',
      'SQL',
      'Operating Systems',
      'Computer Networks',
      'Cybersecurity',
      'Cloud Computing',
      'Artificial Intelligence',
      'Machine Learning',
      'Data Science',
      'Blockchain',
      'Robotics',
      'IoT',
      'Computer Hardware',
      'Software',
      'Tech Companies',
      'Tech History',
    ],
    'Artificial Intelligence': [
      'AI Fundamentals',
      'Machine Learning',
      'Deep Learning',
      'Generative AI',
      'LLMs',
      'Computer Vision',
      'Natural Language Processing',
      'AI Tools',
      'AI Companies',
      'AI History',
      'Famous AI Researchers',
      'AI Applications',
      'Robotics',
      'AI Ethics',
      'AI Terminology',
      'Prompt Engineering',
    ],
    'Sports': [
      'Cricket',
      'Football',
      'Basketball',
      'Tennis',
      'Badminton',
      'Hockey',
      'Volleyball',
      'Formula 1',
      'Athletics',
      'Olympics',
      'Wrestling',
      'Boxing',
      'Golf',
      'Swimming',
      'Chess',
      'Kabaddi',
      'Baseball',
      'Rugby',
      'Cycling',
      'Esports',
      'Famous Athletes',
      'Sports Records',
      'Sports Rules',
      'Sports Stadiums',
      'Sports Trophies',
    ],
    'Movies & Entertainment': [
      'Bollywood',
      'Hollywood',
      'South Indian Cinema',
      'Tamil Cinema',
      'Telugu Cinema',
      'Malayalam Cinema',
      'Kannada Cinema',
      'Korean Cinema',
      'Anime',
      'TV Shows',
      'Web Series',
      'Directors',
      'Actors',
      'Actresses',
      'Movie Characters',
      'Movie Quotes',
      'Movie Awards',
      'Oscar Awards',
      'Famous Films',
      'Film History',
    ],
    'Music': [
      'Indian Music',
      'Bollywood Music',
      'Classical Music',
      'Western Music',
      'Pop',
      'Rock',
      'Hip-Hop',
      'K-Pop',
      'Jazz',
      'Electronic Music',
      'Singers',
      'Bands',
      'Composers',
      'Instruments',
      'Music History',
      'Music Awards',
      'Famous Songs',
      'Lyrics Knowledge',
      'Music Theory',
    ],
    'Literature': [
      'Indian Literature',
      'World Literature',
      'English Literature',
      'Hindi Literature',
      'Urdu Literature',
      'Poetry',
      'Novels',
      'Short Stories',
      'Authors',
      'Poets',
      'Famous Books',
      'Literary Characters',
      'Literary Awards',
      'Booker Prize',
      'Nobel Prize in Literature',
      'Famous Quotes',
      'Shakespeare',
      'R.K. Narayan',
      'George Orwell',
      'Rabindranath Tagore',
    ],
    'Awards & Prizes': [
      'Nobel Prize',
      'Booker Prize',
      'Pulitzer Prize',
      'Oscar Awards',
      'Grammy Awards',
      'Emmy Awards',
      'Golden Globe Awards',
      'BAFTA Awards',
      'Fields Medal',
      'Abel Prize',
      'Turing Award',
      'Breakthrough Prize',
      'Wolf Prize',
      'Templeton Prize',
      'Pritzker Prize',
      'Ballon d\'Or',
      'Laureus Awards',
      'Bharat Ratna',
      'Padma Awards',
      'National Film Awards',
      'Dadasaheb Phalke Award',
      'Ramon Magsaysay Award',
      'Gandhi Peace Prize',
      'International Awards',
      'Indian Awards',
      'Science Awards',
      'Literature Awards',
      'Sports Awards',
    ],
    'General Knowledge': [
      'World GK',
      'India GK',
      'Current GK',
      'Famous People',
      'Famous Places',
      'Famous Books',
      'Famous Inventions',
      'First in the World',
      'First in India',
      'Largest in the World',
      'Smallest in the World',
      'Oldest in the World',
      'Records',
      'Important Dates',
      'Symbols',
      'Nicknames',
      'Superlatives',
      'Miscellaneous GK',
    ],
    'Current Affairs': [
      'India Current Affairs',
      'World Current Affairs',
      'Sports Current Affairs',
      'Science & Technology',
      'Business & Economy',
      'Government & Politics',
      'International Relations',
      'Defence',
      'Space',
      'Awards',
      'Appointments',
      'Important Events',
      'Books & Authors',
      'Obituaries',
      'Summits & Conferences',
    ],
    'Business & Finance': [
      'Stock Market',
      'Investing',
      'Personal Finance',
      'Banking',
      'Cryptocurrency',
      'Economics',
      'Companies',
      'CEOs',
      'Startups',
      'Entrepreneurship',
      'Financial Markets',
      'Currencies',
      'Taxes',
      'Insurance',
      'Accounting',
      'Marketing',
      'Business History',
      'Indian Economy',
      'World Economy',
      'Famous Entrepreneurs',
    ],
    'Banking & Competitive Exams': [
      'Banking Awareness',
      'Financial Awareness',
      'Quantitative Aptitude',
      'Reasoning',
      'English',
      'General Awareness',
      'Computer Awareness',
      'Current Affairs',
      'Static GK',
      'Data Interpretation',
      'SSC GK',
      'UPSC GK',
      'Railway GK',
      'Defence Exams',
      'Government Exams',
    ],
    'Logical Reasoning': [
      'Number Series',
      'Alphabet Series',
      'Coding-Decoding',
      'Blood Relations',
      'Direction Sense',
      'Syllogisms',
      'Analogies',
      'Odd One Out',
      'Seating Arrangement',
      'Ranking',
      'Calendar',
      'Clock',
      'Puzzles',
      'Venn Diagrams',
      'Statement & Conclusion',
      'Pattern Recognition',
    ],
    'Health & Human Body': [
      'Human Anatomy',
      'Human Organs',
      'Diseases',
      'Nutrition',
      'Vitamins',
      'Minerals',
      'First Aid',
      'Medical Science',
      'Human Biology',
      'Blood',
      'Bones',
      'Muscles',
      'Brain',
      'Digestive System',
      'Respiratory System',
      'Famous Medical Discoveries',
    ],
    'Environment & Nature': [
      'Climate',
      'Climate Change',
      'Global Warming',
      'Pollution',
      'Renewable Energy',
      'Wildlife',
      'Endangered Species',
      'Forests',
      'Oceans',
      'Ecosystems',
      'Biodiversity',
      'National Parks',
      'Environmental Organizations',
      'Conservation',
      'Natural Disasters',
    ],
    'Religion & Philosophy': [
      'World Religions',
      'Islamic History',
      'Islamic Civilization',
      'Philosophy',
      'Philosophers',
      'Ancient Philosophies',
      'Ethics',
      'Comparative Religion',
      'Religious Architecture',
      'Religious Literature',
    ],
    'Languages': [
      'English Grammar',
      'English Vocabulary',
      'Synonyms',
      'Antonyms',
      'Idioms',
      'One-Word Substitution',
      'Spelling',
      'Hindi',
      'Urdu',
      'Arabic',
      'French',
      'Spanish',
      'German',
      'Japanese',
      'Korean',
      'World Languages',
      'Translation',
      'Famous Linguists',
    ],
    'Art & Culture': [
      'Painting',
      'Sculpture',
      'Architecture',
      'Photography',
      'Indian Art',
      'World Art',
      'Folk Art',
      'Classical Dance',
      'Indian Dance',
      'World Dance',
      'Museums',
      'Artists',
      'Cultural Heritage',
      'Traditional Clothing',
      'Traditional Food',
      'Festivals',
    ],
    'Space': [
      'Solar System',
      'Planets',
      'Moons',
      'Stars',
      'Galaxies',
      'Black Holes',
      'Space Missions',
      'NASA',
      'ISRO',
      'SpaceX',
      'Astronauts',
      'Rockets',
      'Satellites',
      'Space Exploration',
      'Astronomy',
      'Exoplanets',
      'Famous Space Discoveries',
    ],
    'Fun & Miscellaneous': [
      'Riddles',
      'Brain Teasers',
      'Trivia',
      'Guess the Person',
      'Guess the Place',
      'Guess the Movie',
      'Guess the Song',
      'Guess the Logo',
      'Emoji Quiz',
      'Picture Quiz',
      'True or False',
      'Would You Rather',
      'Mystery Questions',
      'Record Breakers',
      'Weird Facts',
      'Amazing Facts',
    ],
    'Vehicles & Transport': [
      'Cars',
      'Motorcycles',
      'Electric Vehicles',
      'Formula 1 Cars',
      'Aircraft',
      'Airlines',
      'Airports',
      'Trains',
      'Ships',
      'Spacecraft',
      'Automobile Companies',
      'Car Logos',
      'Car History',
      'Famous Vehicles',
      'Transportation History',
    ],
    'Food & Lifestyle': [
      'World Cuisines',
      'Indian Food',
      'Street Food',
      'Fast Food',
      'Fruits',
      'Vegetables',
      'Spices',
      'Desserts',
      'Beverages',
      'Famous Dishes',
      'Food Origins',
      'Cooking',
      'Nutrition',
      'Restaurant Trivia',
      'Food Around the World',
    ],
    'Famous People': [
      'Scientists',
      'Inventors',
      'Politicians',
      'Leaders',
      'Actors',
      'Actresses',
      'Singers',
      'Athletes',
      'Authors',
      'Entrepreneurs',
      'CEOs',
      'Philosophers',
      'Artists',
      'Explorers',
      'Astronauts',
      'Historical Figures',
    ],
    'Politics & Government': [
      'Indian Constitution',
      'Indian Parliament',
      'President & Vice President',
      'Prime Ministers',
      'State Governments',
      'Elections',
      'Political Systems',
      'World Governments',
      'United Nations',
      'International Organizations',
      'Democracy',
      'International Relations',
      'Government Schemes',
      'Important Acts',
      'Political History',
    ],
    'International Organizations': [
      'United Nations',
      'WHO',
      'UNESCO',
      'UNICEF',
      'IMF',
      'World Bank',
      'WTO',
      'NATO',
      'SAARC',
      'ASEAN',
      'European Union',
      'G7',
      'G20',
      'BRICS',
      'OPEC',
      'Red Cross',
    ],
    'Education & Academics': [
      'Physics',
      'Chemistry',
      'Biology',
      'Mathematics',
      'Computer Science',
      'Geography',
      'History',
      'Political Science',
      'Economics',
      'Psychology',
      'Sociology',
      'Environmental Studies',
      'English',
      'General Aptitude',
      'Research & Methodology',
    ],
  };

  /// Total number of subjects across every domain in the tree.
  static int get subjectCount =>
      tree.values.fold<int>(0, (sum, list) => sum + list.length);

  /// Total number of domains in the tree.
  static int get domainCount => tree.length;
}
